### PR TITLE
build #196

### PR DESCRIPTION
**Pull request by wjmelements**
ptal @Arachnid 

#196 did not meteor-build-client. This builds it.

### CODE REVIEW

**Comment by wjmelements** [comment]
meteor-build-client rm's docs/CNAME, which didn't seem desirable, so I did not commit that file.

**Review by Arachnid — APPROVED** [review]
Thank you again!

**Comment by Arachnid** [comment]
It looks like the build wasn't constructed correctly - it broke the whole app. :

**Comment by wjmelements** [comment]
:(

**Pull request merged**
